import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'features/authentication/screens/sign_in_screen.dart';
import 'features/home/screens/home_screen.dart';
import 'firebase_options.dart';  // This file will be generated by flutterfire configure

// Global environment variables
late final String FIREBASE_API_KEY;
late final String FIREBASE_APP_ID;
late final String FIREBASE_MESSAGING_SENDER_ID;
late final String FIREBASE_PROJECT_ID;
late final String FIREBASE_STORAGE_BUCKET;
late final String FIREBASE_AUTH_DOMAIN;

// Set this to false to bypass App Check during development
const bool ENABLE_APP_CHECK = false;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Load .env first
  await dotenv.load(fileName: ".env");
  
  // Then access env variables
  FIREBASE_API_KEY = dotenv.env['FIREBASE_API_KEY']!;
  FIREBASE_APP_ID = dotenv.env['FIREBASE_APP_ID']!;
  FIREBASE_MESSAGING_SENDER_ID = dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!;
  FIREBASE_PROJECT_ID = dotenv.env['FIREBASE_PROJECT_ID']!;
  FIREBASE_STORAGE_BUCKET = dotenv.env['FIREBASE_STORAGE_BUCKET']!;
  FIREBASE_AUTH_DOMAIN = dotenv.env['FIREBASE_AUTH_DOMAIN']!;

  // Initialize Firebase first
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  if (ENABLE_APP_CHECK) {
    debugPrint('\n=== STARTING APP CHECK INITIALIZATION ===');
    try {
      debugPrint('Activating App Check...');
      await FirebaseAppCheck.instance.activate(
        androidProvider: AndroidProvider.debug,
      );

      if (dotenv.env['FIREBASE_APP_CHECK_DEBUG_TOKEN'] != null) {
        debugPrint('Debug token from env: ${dotenv.env['FIREBASE_APP_CHECK_DEBUG_TOKEN']}');
      }

      debugPrint('Getting App Check token...');
      final token = await FirebaseAppCheck.instance.getToken();
      debugPrint('✅ App Check Token: $token');
      debugPrint('✅ Firebase App Check initialized successfully');
    } catch (e) {
      debugPrint('❌ App Check Error: $e');
    }
    debugPrint('=== FINISHED APP CHECK INITIALIZATION ===\n');
  } else {
    debugPrint('\n=== APP CHECK DISABLED FOR DEVELOPMENT ===\n');
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TikTok Clone - Hot Reload Test',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: SignInScreen(),
      routes: {
        '/home': (context) => const HomeScreen(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
