version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
      - ./app:/app/app  # For development hot-reload
      - .:/app  # Mount entire directory for hot reload
    command: python -m flask --app app:create_app run --host=0.0.0.0 --port=80 --debug
    restart: unless-stopped 